from collections import OrderedDict 

PROFESSIONAL_REMITTANCE_ADVICE = OrderedDict()

PROFESSIONAL_REMITTANCE_ADVICE['LASTNAME_PATIENTACCOUNT']           = ['LAST NAME','PATIENT ACCOUNT']
PROFESSIONAL_REMITTANCE_ADVICE['FIRSTNAME_MEMBERID']                = ['FIRST NAME','MEMBER ID']
PROFESSIONAL_REMITTANCE_ADVICE['CLAIMNUMBER_RECVDDT_SERVPROV']      = ['CLAIM NUMBER','RECVD DT','SERV PROV']
PROFESSIONAL_REMITTANCE_ADVICE['DATEOFSERVICE_FROMTHRU']            = ['FROM','THRU']
PROFESSIONAL_REMITTANCE_ADVICE['PROCEDURE_MODIFIER']                = ['PROCEDURE','MODIFIER']
PROFESSIONAL_REMITTANCE_ADVICE['TOTALCHARGES']                      = ['TOTOL CHARGES']
PROFESSIONAL_REMITTANCE_ADVICE['PATIENTNONCOVERED']                 = ['PATIENT NON COVERED']
PROFESSIONAL_REMITTANCE_ADVICE['NOTE']                              = ['NOTE']
PROFESSIONAL_REMITTANCE_ADVICE['CONTRACTWRITEOFF']                  = ['CONTRACT WRITE OFF']
PROFESSIONAL_REMITTANCE_ADVICE['NOTE2']                             = ['NOTE2']
PROFESSIONAL_REMITTANCE_ADVICE['PATIENTDEDCOPAY']                   = ['PATIENT DED COPY']
PROFESSIONAL_REMITTANCE_ADVICE['PATIENTCOINS']                      = ['PATIENT COINS']
PROFESSIONAL_REMITTANCE_ADVICE['OTHERINSURANCEMEDICARE']            = ['OTHER INSURANCE MEDICARE']
PROFESSIONAL_REMITTANCE_ADVICE['CLIAMPAID_INTERESTPAID']            = ['CLAIM PAID','INTEREST PAID']
PROFESSIONAL_REMITTANCE_ADVICE['PATIENTOWES']                       = ['PATIENT OWES']



if __name__ == "__main__":
    print('--start--')

    print(PROFESSIONAL_REMITTANCE_ADVICE)
    print(PROFESSIONAL_REMITTANCE_ADVICE.keys())
    print(PROFESSIONAL_REMITTANCE_ADVICE.values())
    print(type(tuple(PROFESSIONAL_REMITTANCE_ADVICE.values()) ))
    print(tuple(PROFESSIONAL_REMITTANCE_ADVICE.values())[-1])